### ISSUE TITLE
build locally shall ignore the step of upload codecov result. 

### ISSUE THREAD

**Issue by kuanf** [IBM/go-repo-template#21] opened 2019-10-21 19:02 UTC
otherwise, will see 

```
common/scripts/codecov.sh: line 150: CODECOV_TOKEN: unbound variable
```

**Comment by itdove** [comment] 2019-10-22 02:45
Duplicate of #23

**Comment by kuanf** [comment] 2019-10-25 14:54
let's close this one and address together with #23

**Closed** 2019-10-25 14:54 UTC
